version: '3'

services:
  fivem:
    image: spritsail/fivem
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "/home/vsrapFivem/fivem:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENCE_KEY: "license-key-here"
